apiVersion: apps/v1
kind: Deployment
metadata:
  name: devspace-dev
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: devspace-dev
  template:
    metadata:
      labels:
        app: devspace-dev
    spec:
      containers:
      - name: java-app
        #image: nexus.dspace.kt.co.kr/library/nginx:1.27.0
        image: acrdevspace.azurecr.io/devspace/java-maven:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: devspace-acr
