apiVersion: apps/v1
kind: Deployment
metadata:
  name: devspace-dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: devspace-dev
  template:
    metadata:
      labels:
        app: devspace-dev
    spec:
      containers:
      - name: nginx
        #image: devspacemyregistry.azurecr.io/kthamseungwoo/edu1:devspace1
        image: nexus.dspace.kt.co.kr/library/nginx:1.27.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: devspace-nexus
