apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: devspacemyregistry.azurecr.io/kthamseungwoo/edu1:devspace1
  newTag: "devspace1"
