apiVersion: v1
kind: Service
metadata:
  name: devspace-dev
  labels: # service monitor 의 selector 를 위하여 생성
    app: devspace-dev
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: devspace-dev
  type: ClusterIP
